---
- hosts: all
  vars:
    base64_manifest: "{{ aws_workshops_data.base64_manifest }}"
    redhat_username: "{{ aws_workshops_data.redhat_username }}"
    redhat_password: "{{ aws_workshops_data.redhat_password }}"
    offline_token: "{{ aws_workshops_data.offline_token }}"
    developer_mode: true
  tasks:
    - name: Ensure the aws folder exist in HOME
      file:
        path: '{{ ansible_env.HOME }}/.aws'
        state: directory

    - name: Lay the credential file
      copy:
        dest: '{{ ansible_env.HOME }}/.aws/credentials'
        content: |
          [default]
          aws_access_key_id = {{ aws_workshops_data.aws_access_key }}
          aws_secret_access_key = {{ aws_workshops_data.aws_secret_key }}

    - name: Run tox
      include_role:
        name: tox
      vars:
        tox_envlist: 'workshop-{{ workshop_type }}'
        tox_environment:
          WORKSHOPS_CHANGE_ID: '{{ zuul.change | int }}'
        test_setup_skip: true
        zuul_work_dir: "{{ zuul.project.src_dir }}"
