---
- hosts: localhost
  gather_facts: false
  tasks:
    - when: zuul.project.canonical_hostname == "github.com"
      block:
        - name: Retrieve the details about the Github project
          uri:
            url: "https://api.github.com/repos/{{ zuul.project.name }}"
            return_content: true
          register: project_details
        - name: Run check_changelog_fragment role
          include_role:
            name: check_changelog_fragment
          vars:
            check_changelog_fragment__git_directory: "{{ zuul.executor.src_root }}/{{ zuul.project.canonical_name }}"
            check_changelog_fragment__target_branch: "{{ project_details.json.default_branch }}"
