---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Run Zuul manifest role
      include_role:
        name: generate-zuul-manifest

    - name: Set zuul-log-path fact
      include_role:
        name: set-zuul-log-path-fact
      vars:
        zuul_log_path_shard_build: true

    - name: Run upload-logs-swift role
      no_log: true
      include_role:
        name: upload-logs-swift
      vars:
        zuul_log_partition: true
        zuul_log_container: ansible
        zuul_log_cloud_config: "{{ item }}"
        zuul_log_delete_after: 7776000
      with_random_choice:
        - "{{ rackspace_dfw_clouds_yaml }}"
        - "{{ rackspace_iad_clouds_yaml }}"
        - "{{ rackspace_ord_clouds_yaml }}"
