---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Run emit-job-header role
      include_role:
        name: emit-job-header
      vars:
        zuul_log_url: https://logs.zuul.ansible.com

    - name: Run log-inventory role
      include_role:
        name: log-inventory

- hosts: all:!appliance
  tasks:
    - name: Run add-build-sshkey role (RSA)
      include_role:
        name: add-build-sshkey
      vars:
        zuul_ssh_key_size: 2048

    - name: Run add-build-sshkey role (ECDSA)
      include_role:
        name: add-build-sshkey
      vars:
        zuul_ssh_key_algorithm: ecdsa
        zuul_ssh_key_size: 521

    - name: Run start-zuul-console role
      include_role:
        name: start-zuul-console

- hosts: all:!appliance*
  tasks:
    - name: Install git (AWS EC2)
      package:
        name: git
        state: present
      become: true
      # cloud-init may also be running in parallel
      register: result
      retries: 6
      delay: 10
      until: result is not failed
      when: nodepool.provider.startswith("ec2")
    - name: Run prepare-workspace-git role
      include_role:
        name: prepare-workspace-git
